class ExchangeRateModel {
  final String  id;
  final String  clientId;
  final String  companyId;
  final String  locationId;
  final String  rateDate;       // 'YYYY-MM-DD'
  final String  fromCurrency;
  final String  toCurrency;
  final double  buyingRate;
  final double  sellingRate;
  final double? midRate;        // generated by DB; null when read from local cache
  final String  source;
  final bool    isDeleted;

  const ExchangeRateModel({
    required this.id,
    required this.clientId,
    required this.companyId,
    required this.locationId,
    required this.rateDate,
    required this.fromCurrency,
    required this.toCurrency,
    required this.buyingRate,
    required this.sellingRate,
    this.midRate,
    required this.source,
    required this.isDeleted,
  });

  factory ExchangeRateModel.fromJson(Map<String, dynamic> j) => ExchangeRateModel(
        id:           j['id']            as String,
        clientId:     j['client_id']     as String,
        companyId:    j['company_id']    as String,
        locationId:   j['location_id']   as String,
        rateDate:     j['rate_date']     as String,
        fromCurrency: j['from_currency'] as String,
        toCurrency:   j['to_currency']   as String,
        buyingRate:   (j['buying_rate']  as num).toDouble(),
        sellingRate:  (j['selling_rate'] as num).toDouble(),
        midRate:      j['mid_rate'] != null ? (j['mid_rate'] as num).toDouble() : null,
        source:       j['source']        as String? ?? 'MANUAL',
        isDeleted:    j['is_deleted']    as bool?   ?? false,
      );

  Map<String, dynamic> toJson() => {
        'id':            id,
        'client_id':     clientId,
        'company_id':    companyId,
        'location_id':   locationId,
        'rate_date':     rateDate,
        'from_currency': fromCurrency,
        'to_currency':   toCurrency,
        'buying_rate':   buyingRate,
        'selling_rate':  sellingRate,
        if (midRate != null) 'mid_rate': midRate,
        'source':        source,
        'is_deleted':    isDeleted,
      };
}
