-- ============================================================
-- 009_divisions.sql
-- rim_divisions: global reference table (no client/company on seeded rows)
-- System rows: is_system=true, client_id=NULL, company_id=NULL
-- Custom rows: is_system=false, client_id=X, company_id=Y
--
-- QUERY PATTERN (use everywhere):
--   WHERE country_code = ? AND (is_system = true OR (client_id = ? AND company_id = ?))
-- ============================================================

-- Shared trigger function — sets updated_at = now() on every UPDATE.
-- Defined here once; reused by 010_cities.sql and any future table.
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS rim_divisions (
    id              uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id       uuid        REFERENCES ric_clients(id),    -- NULL for system rows
    company_id      uuid        REFERENCES ric_companies(id),  -- NULL for system rows
    country_code    text        NOT NULL,
    division_code   text        NOT NULL,
    division_name   text        NOT NULL,
    division_type   text        NOT NULL DEFAULT 'Province',
    is_system       boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    created_by      uuid,
    updated_by      uuid
);

-- System rows: unique by country + code
CREATE UNIQUE INDEX idx_rim_divisions_system_uniq
    ON rim_divisions (country_code, division_code)
    WHERE is_system = true;

-- Custom rows: unique by tenant + country + code
CREATE UNIQUE INDEX idx_rim_divisions_custom_uniq
    ON rim_divisions (client_id, company_id, country_code, division_code)
    WHERE is_system = false;

CREATE INDEX idx_rim_divisions_country  ON rim_divisions (country_code);
CREATE INDEX idx_rim_divisions_tenant   ON rim_divisions (client_id, company_id);

CREATE TRIGGER trg_rim_divisions_updated_at
    BEFORE UPDATE ON rim_divisions
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── Seed: System Divisions ────────────────────────────────────────────
-- is_system=true, client_id=NULL, company_id=NULL

INSERT INTO rim_divisions (country_code, division_code, division_name, division_type, is_system) VALUES

-- ── DRC — 26 Provinces ───────────────────────────────────────────────
('CD','CD-BU','Bas-Uele',           'Province', true),
('CD','CD-EQ','Équateur',           'Province', true),
('CD','CD-HK','Haut-Katanga',       'Province', true),
('CD','CD-HL','Haut-Lomami',        'Province', true),
('CD','CD-HU','Haut-Uele',          'Province', true),
('CD','CD-IT','Ituri',              'Province', true),
('CD','CD-KA','Kasaï',              'Province', true),
('CD','CD-KC','Kasaï-Central',      'Province', true),
('CD','CD-KE','Kasaï-Oriental',     'Province', true),
('CD','CD-KN','Kinshasa',           'Province', true),
('CD','CD-KG','Kongo Central',      'Province', true),
('CD','CD-KW','Kwango',             'Province', true),
('CD','CD-KL','Kwilu',              'Province', true),
('CD','CD-LO','Lomami',             'Province', true),
('CD','CD-LU','Lualaba',            'Province', true),
('CD','CD-MN','Mai-Ndombe',         'Province', true),
('CD','CD-MA','Maniema',            'Province', true),
('CD','CD-MO','Mongala',            'Province', true),
('CD','CD-NK','Nord-Kivu',          'Province', true),
('CD','CD-NU','Nord-Ubangi',        'Province', true),
('CD','CD-SA','Sankuru',            'Province', true),
('CD','CD-SK','Sud-Kivu',           'Province', true),
('CD','CD-SU','Sud-Ubangi',         'Province', true),
('CD','CD-TA','Tanganyika',         'Province', true),
('CD','CD-TO','Tshopo',             'Province', true),
('CD','CD-TU','Tshuapa',            'Province', true),

-- ── Zambia — 10 Provinces ────────────────────────────────────────────
('ZM','ZM-CE','Central',            'Province', true),
('ZM','ZM-CB','Copperbelt',         'Province', true),
('ZM','ZM-EA','Eastern',            'Province', true),
('ZM','ZM-LU','Luapula',            'Province', true),
('ZM','ZM-LS','Lusaka',             'Province', true),
('ZM','ZM-MU','Muchinga',           'Province', true),
('ZM','ZM-NO','Northern',           'Province', true),
('ZM','ZM-NW','North-Western',      'Province', true),
('ZM','ZM-SO','Southern',           'Province', true),
('ZM','ZM-WE','Western',            'Province', true),

-- ── South Africa — 9 Provinces ───────────────────────────────────────
('ZA','ZA-EC','Eastern Cape',       'Province', true),
('ZA','ZA-FS','Free State',         'Province', true),
('ZA','ZA-GT','Gauteng',            'Province', true),
('ZA','ZA-KN','KwaZulu-Natal',      'Province', true),
('ZA','ZA-LP','Limpopo',            'Province', true),
('ZA','ZA-MP','Mpumalanga',         'Province', true),
('ZA','ZA-NW','North West',         'Province', true),
('ZA','ZA-NC','Northern Cape',      'Province', true),
('ZA','ZA-WC','Western Cape',       'Province', true),

-- ── Zimbabwe — 10 Provinces ──────────────────────────────────────────
('ZW','ZW-BU','Bulawayo',           'Province', true),
('ZW','ZW-HA','Harare',             'Province', true),
('ZW','ZW-MA','Manicaland',         'Province', true),
('ZW','ZW-MC','Mashonaland Central','Province', true),
('ZW','ZW-ME','Mashonaland East',   'Province', true),
('ZW','ZW-MW','Mashonaland West',   'Province', true),
('ZW','ZW-MV','Masvingo',           'Province', true),
('ZW','ZW-MN','Matabeleland North', 'Province', true),
('ZW','ZW-MS','Matabeleland South', 'Province', true),
('ZW','ZW-MI','Midlands',           'Province', true),

-- ── Tanzania — 31 Regions ────────────────────────────────────────────
('TZ','TZ-01','Arusha',             'Region', true),
('TZ','TZ-02','Dar es Salaam',      'Region', true),
('TZ','TZ-03','Dodoma',             'Region', true),
('TZ','TZ-04','Geita',              'Region', true),
('TZ','TZ-05','Iringa',             'Region', true),
('TZ','TZ-06','Kagera',             'Region', true),
('TZ','TZ-07','Katavi',             'Region', true),
('TZ','TZ-08','Kigoma',             'Region', true),
('TZ','TZ-09','Kilimanjaro',        'Region', true),
('TZ','TZ-10','Lindi',              'Region', true),
('TZ','TZ-11','Manyara',            'Region', true),
('TZ','TZ-12','Mara',               'Region', true),
('TZ','TZ-13','Mbeya',              'Region', true),
('TZ','TZ-14','Morogoro',           'Region', true),
('TZ','TZ-15','Mtwara',             'Region', true),
('TZ','TZ-16','Mwanza',             'Region', true),
('TZ','TZ-17','Njombe',             'Region', true),
('TZ','TZ-18','Pemba North',        'Region', true),
('TZ','TZ-19','Pemba South',        'Region', true),
('TZ','TZ-20','Pwani',              'Region', true),
('TZ','TZ-21','Rukwa',              'Region', true),
('TZ','TZ-22','Ruvuma',             'Region', true),
('TZ','TZ-23','Shinyanga',          'Region', true),
('TZ','TZ-24','Simiyu',             'Region', true),
('TZ','TZ-25','Singida',            'Region', true),
('TZ','TZ-26','Songwe',             'Region', true),
('TZ','TZ-27','Tabora',             'Region', true),
('TZ','TZ-28','Tanga',              'Region', true),
('TZ','TZ-29','Unguja North',       'Region', true),
('TZ','TZ-30','Unguja South',       'Region', true),
('TZ','TZ-31','Unguja West',        'Region', true),

-- ── Kenya — 47 Counties ──────────────────────────────────────────────
('KE','KE-01','Mombasa',            'County', true),
('KE','KE-02','Kwale',              'County', true),
('KE','KE-03','Kilifi',             'County', true),
('KE','KE-04','Tana River',         'County', true),
('KE','KE-05','Lamu',               'County', true),
('KE','KE-06','Taita-Taveta',       'County', true),
('KE','KE-07','Garissa',            'County', true),
('KE','KE-08','Wajir',              'County', true),
('KE','KE-09','Mandera',            'County', true),
('KE','KE-10','Marsabit',           'County', true),
('KE','KE-11','Isiolo',             'County', true),
('KE','KE-12','Meru',               'County', true),
('KE','KE-13','Tharaka-Nithi',      'County', true),
('KE','KE-14','Embu',               'County', true),
('KE','KE-15','Kitui',              'County', true),
('KE','KE-16','Machakos',           'County', true),
('KE','KE-17','Makueni',            'County', true),
('KE','KE-18','Nyandarua',          'County', true),
('KE','KE-19','Nyeri',              'County', true),
('KE','KE-20','Kirinyaga',          'County', true),
('KE','KE-21','Murang''a',          'County', true),
('KE','KE-22','Kiambu',             'County', true),
('KE','KE-23','Turkana',            'County', true),
('KE','KE-24','West Pokot',         'County', true),
('KE','KE-25','Samburu',            'County', true),
('KE','KE-26','Trans-Nzoia',        'County', true),
('KE','KE-27','Uasin Gishu',        'County', true),
('KE','KE-28','Elgeyo-Marakwet',    'County', true),
('KE','KE-29','Nandi',              'County', true),
('KE','KE-30','Baringo',            'County', true),
('KE','KE-31','Laikipia',           'County', true),
('KE','KE-32','Nakuru',             'County', true),
('KE','KE-33','Narok',              'County', true),
('KE','KE-34','Kajiado',            'County', true),
('KE','KE-35','Kericho',            'County', true),
('KE','KE-36','Bomet',              'County', true),
('KE','KE-37','Kakamega',           'County', true),
('KE','KE-38','Vihiga',             'County', true),
('KE','KE-39','Bungoma',            'County', true),
('KE','KE-40','Busia',              'County', true),
('KE','KE-41','Siaya',              'County', true),
('KE','KE-42','Kisumu',             'County', true),
('KE','KE-43','Homa Bay',           'County', true),
('KE','KE-44','Migori',             'County', true),
('KE','KE-45','Kisii',              'County', true),
('KE','KE-46','Nyamira',            'County', true),
('KE','KE-47','Nairobi',            'County', true),

-- ── Nigeria — 36 States + FCT ────────────────────────────────────────
('NG','NG-AB','Abia',               'State', true),
('NG','NG-AD','Adamawa',            'State', true),
('NG','NG-AK','Akwa Ibom',          'State', true),
('NG','NG-AN','Anambra',            'State', true),
('NG','NG-BA','Bauchi',             'State', true),
('NG','NG-BY','Bayelsa',            'State', true),
('NG','NG-BE','Benue',              'State', true),
('NG','NG-BO','Borno',              'State', true),
('NG','NG-CR','Cross River',        'State', true),
('NG','NG-DE','Delta',              'State', true),
('NG','NG-EB','Ebonyi',             'State', true),
('NG','NG-ED','Edo',                'State', true),
('NG','NG-EK','Ekiti',              'State', true),
('NG','NG-EN','Enugu',              'State', true),
('NG','NG-FC','Federal Capital Territory','State', true),
('NG','NG-GO','Gombe',              'State', true),
('NG','NG-IM','Imo',                'State', true),
('NG','NG-JI','Jigawa',             'State', true),
('NG','NG-KD','Kaduna',             'State', true),
('NG','NG-KN','Kano',               'State', true),
('NG','NG-KT','Katsina',            'State', true),
('NG','NG-KE','Kebbi',              'State', true),
('NG','NG-KO','Kogi',               'State', true),
('NG','NG-KW','Kwara',              'State', true),
('NG','NG-LA','Lagos',              'State', true),
('NG','NG-NA','Nasarawa',           'State', true),
('NG','NG-NI','Niger',              'State', true),
('NG','NG-OG','Ogun',               'State', true),
('NG','NG-ON','Ondo',               'State', true),
('NG','NG-OS','Osun',               'State', true),
('NG','NG-OY','Oyo',                'State', true),
('NG','NG-PL','Plateau',            'State', true),
('NG','NG-RI','Rivers',             'State', true),
('NG','NG-SO','Sokoto',             'State', true),
('NG','NG-TA','Taraba',             'State', true),
('NG','NG-YO','Yobe',               'State', true),
('NG','NG-ZA','Zamfara',            'State', true),

-- ── Ethiopia — 14 Regions ────────────────────────────────────────────
('ET','ET-AA','Addis Ababa',              'Region', true),
('ET','ET-AF','Afar',                     'Region', true),
('ET','ET-AM','Amhara',                   'Region', true),
('ET','ET-BE','Benishangul-Gumuz',        'Region', true),
('ET','ET-CE','Central Ethiopia',         'Region', true),
('ET','ET-DD','Dire Dawa',                'Region', true),
('ET','ET-GA','Gambela',                  'Region', true),
('ET','ET-HA','Harari',                   'Region', true),
('ET','ET-OR','Oromia',                   'Region', true),
('ET','ET-SI','Sidama',                   'Region', true),
('ET','ET-SN','South Ethiopia',           'Region', true),
('ET','ET-SW','South West Ethiopia',      'Region', true),
('ET','ET-SO','Somali',                   'Region', true),
('ET','ET-TI','Tigray',                   'Region', true),

-- ── Uganda — 4 Regions ───────────────────────────────────────────────
('UG','UG-C','Central',                   'Region', true),
('UG','UG-E','Eastern',                   'Region', true),
('UG','UG-N','Northern',                  'Region', true),
('UG','UG-W','Western',                   'Region', true),

-- ── Rwanda — 5 Provinces ─────────────────────────────────────────────
('RW','RW-01','Kigali City',              'Province', true),
('RW','RW-02','Eastern Province',         'Province', true),
('RW','RW-03','Northern Province',        'Province', true),
('RW','RW-04','Southern Province',        'Province', true),
('RW','RW-05','Western Province',         'Province', true),

-- ── Ghana — 16 Regions ───────────────────────────────────────────────
('GH','GH-AH','Ahafo',                   'Region', true),
('GH','GH-AS','Ashanti',                 'Region', true),
('GH','GH-BO','Bono',                    'Region', true),
('GH','GH-BE','Bono East',               'Region', true),
('GH','GH-CE','Central',                 'Region', true),
('GH','GH-EA','Eastern',                 'Region', true),
('GH','GH-GT','Greater Accra',           'Region', true),
('GH','GH-NE','North East',              'Region', true),
('GH','GH-NO','Northern',                'Region', true),
('GH','GH-OT','Oti',                     'Region', true),
('GH','GH-SA','Savannah',                'Region', true),
('GH','GH-UE','Upper East',              'Region', true),
('GH','GH-UW','Upper West',              'Region', true),
('GH','GH-TV','Volta',                   'Region', true),
('GH','GH-WN','Western North',           'Region', true),
('GH','GH-WE','Western',                 'Region', true),

-- ── Mozambique — 10 Provinces + Maputo City ───────────────────────────
('MZ','MZ-A', 'Niassa',                  'Province', true),
('MZ','MZ-B', 'Sofala',                  'Province', true),
('MZ','MZ-G', 'Gaza',                    'Province', true),
('MZ','MZ-I', 'Inhambane',               'Province', true),
('MZ','MZ-L', 'Maputo Province',         'Province', true),
('MZ','MZ-MPM','Maputo City',            'Province', true),
('MZ','MZ-N', 'Nampula',                 'Province', true),
('MZ','MZ-P', 'Cabo Delgado',            'Province', true),
('MZ','MZ-Q', 'Zambézia',                'Province', true),
('MZ','MZ-S', 'Manica',                  'Province', true),
('MZ','MZ-T', 'Tete',                    'Province', true),

-- ── Angola — 18 Provinces ────────────────────────────────────────────
('AO','AO-BGO','Bengo',                  'Province', true),
('AO','AO-BGU','Benguela',               'Province', true),
('AO','AO-BIE','Bié',                    'Province', true),
('AO','AO-CAB','Cabinda',                'Province', true),
('AO','AO-CCU','Cuando Cubango',         'Province', true),
('AO','AO-CNO','Cuanza Norte',           'Province', true),
('AO','AO-CUS','Cuanza Sul',             'Province', true),
('AO','AO-CNN','Cunene',                 'Province', true),
('AO','AO-HUA','Huambo',                 'Province', true),
('AO','AO-HUI','Huíla',                  'Province', true),
('AO','AO-LUA','Luanda',                 'Province', true),
('AO','AO-LNO','Lunda Norte',            'Province', true),
('AO','AO-LSU','Lunda Sul',              'Province', true),
('AO','AO-MAL','Malanje',                'Province', true),
('AO','AO-MOX','Moxico',                 'Province', true),
('AO','AO-NAM','Namibe',                 'Province', true),
('AO','AO-UIG','Uíge',                   'Province', true),
('AO','AO-ZAI','Zaire',                  'Province', true),

-- ── Cameroon — 10 Regions ────────────────────────────────────────────
('CM','CM-AD','Adamaoua',                'Region', true),
('CM','CM-CE','Centre',                  'Region', true),
('CM','CM-EN','Far North',               'Region', true),
('CM','CM-ES','East',                    'Region', true),
('CM','CM-LT','Littoral',                'Region', true),
('CM','CM-NO','North',                   'Region', true),
('CM','CM-NW','North West',              'Region', true),
('CM','CM-OU','West',                    'Region', true),
('CM','CM-SU','South',                   'Region', true),
('CM','CM-SW','South West',              'Region', true),

-- ── USA — 50 States + DC ─────────────────────────────────────────────
('US','US-AL','Alabama',                 'State', true),
('US','US-AK','Alaska',                  'State', true),
('US','US-AZ','Arizona',                 'State', true),
('US','US-AR','Arkansas',                'State', true),
('US','US-CA','California',              'State', true),
('US','US-CO','Colorado',                'State', true),
('US','US-CT','Connecticut',             'State', true),
('US','US-DE','Delaware',                'State', true),
('US','US-DC','District of Columbia',    'State', true),
('US','US-FL','Florida',                 'State', true),
('US','US-GA','Georgia',                 'State', true),
('US','US-HI','Hawaii',                  'State', true),
('US','US-ID','Idaho',                   'State', true),
('US','US-IL','Illinois',                'State', true),
('US','US-IN','Indiana',                 'State', true),
('US','US-IA','Iowa',                    'State', true),
('US','US-KS','Kansas',                  'State', true),
('US','US-KY','Kentucky',                'State', true),
('US','US-LA','Louisiana',               'State', true),
('US','US-ME','Maine',                   'State', true),
('US','US-MD','Maryland',                'State', true),
('US','US-MA','Massachusetts',           'State', true),
('US','US-MI','Michigan',                'State', true),
('US','US-MN','Minnesota',               'State', true),
('US','US-MS','Mississippi',             'State', true),
('US','US-MO','Missouri',                'State', true),
('US','US-MT','Montana',                 'State', true),
('US','US-NE','Nebraska',                'State', true),
('US','US-NV','Nevada',                  'State', true),
('US','US-NH','New Hampshire',           'State', true),
('US','US-NJ','New Jersey',              'State', true),
('US','US-NM','New Mexico',              'State', true),
('US','US-NY','New York',                'State', true),
('US','US-NC','North Carolina',          'State', true),
('US','US-ND','North Dakota',            'State', true),
('US','US-OH','Ohio',                    'State', true),
('US','US-OK','Oklahoma',                'State', true),
('US','US-OR','Oregon',                  'State', true),
('US','US-PA','Pennsylvania',            'State', true),
('US','US-RI','Rhode Island',            'State', true),
('US','US-SC','South Carolina',          'State', true),
('US','US-SD','South Dakota',            'State', true),
('US','US-TN','Tennessee',               'State', true),
('US','US-TX','Texas',                   'State', true),
('US','US-UT','Utah',                    'State', true),
('US','US-VT','Vermont',                 'State', true),
('US','US-VA','Virginia',                'State', true),
('US','US-WA','Washington',              'State', true),
('US','US-WV','West Virginia',           'State', true),
('US','US-WI','Wisconsin',               'State', true),
('US','US-WY','Wyoming',                 'State', true),

-- ── Canada — 10 Provinces + 3 Territories ────────────────────────────
('CA','CA-AB','Alberta',                      'Province',  true),
('CA','CA-BC','British Columbia',             'Province',  true),
('CA','CA-MB','Manitoba',                     'Province',  true),
('CA','CA-NB','New Brunswick',                'Province',  true),
('CA','CA-NL','Newfoundland and Labrador',    'Province',  true),
('CA','CA-NS','Nova Scotia',                  'Province',  true),
('CA','CA-NT','Northwest Territories',        'Territory', true),
('CA','CA-NU','Nunavut',                      'Territory', true),
('CA','CA-ON','Ontario',                      'Province',  true),
('CA','CA-PE','Prince Edward Island',         'Province',  true),
('CA','CA-QC','Quebec',                       'Province',  true),
('CA','CA-SK','Saskatchewan',                 'Province',  true),
('CA','CA-YT','Yukon',                        'Territory', true),

-- ── India — 28 States + 8 Union Territories ──────────────────────────
('IN','IN-AN','Andaman and Nicobar Islands',          'Union Territory', true),
('IN','IN-AP','Andhra Pradesh',                       'State',           true),
('IN','IN-AR','Arunachal Pradesh',                    'State',           true),
('IN','IN-AS','Assam',                                'State',           true),
('IN','IN-BR','Bihar',                                'State',           true),
('IN','IN-CH','Chandigarh',                           'Union Territory', true),
('IN','IN-CG','Chhattisgarh',                         'State',           true),
('IN','IN-DH','Dadra and Nagar Haveli',               'Union Territory', true),
('IN','IN-DL','Delhi',                                'Union Territory', true),
('IN','IN-GA','Goa',                                  'State',           true),
('IN','IN-GJ','Gujarat',                              'State',           true),
('IN','IN-HR','Haryana',                              'State',           true),
('IN','IN-HP','Himachal Pradesh',                     'State',           true),
('IN','IN-JK','Jammu and Kashmir',                    'Union Territory', true),
('IN','IN-JH','Jharkhand',                            'State',           true),
('IN','IN-KA','Karnataka',                            'State',           true),
('IN','IN-KL','Kerala',                               'State',           true),
('IN','IN-LA','Ladakh',                               'Union Territory', true),
('IN','IN-LD','Lakshadweep',                          'Union Territory', true),
('IN','IN-MP','Madhya Pradesh',                       'State',           true),
('IN','IN-MH','Maharashtra',                          'State',           true),
('IN','IN-MN','Manipur',                              'State',           true),
('IN','IN-ML','Meghalaya',                            'State',           true),
('IN','IN-MZ','Mizoram',                              'State',           true),
('IN','IN-NL','Nagaland',                             'State',           true),
('IN','IN-OR','Odisha',                               'State',           true),
('IN','IN-PY','Puducherry',                           'Union Territory', true),
('IN','IN-PB','Punjab',                               'State',           true),
('IN','IN-RJ','Rajasthan',                            'State',           true),
('IN','IN-SK','Sikkim',                               'State',           true),
('IN','IN-TN','Tamil Nadu',                           'State',           true),
('IN','IN-TG','Telangana',                            'State',           true),
('IN','IN-TR','Tripura',                              'State',           true),
('IN','IN-UP','Uttar Pradesh',                        'State',           true),
('IN','IN-UT','Uttarakhand',                          'State',           true),
('IN','IN-WB','West Bengal',                          'State',           true),

-- ── UAE — 7 Emirates ─────────────────────────────────────────────────
('AE','AE-AZ','Abu Dhabi',               'Emirate', true),
('AE','AE-AJ','Ajman',                   'Emirate', true),
('AE','AE-DU','Dubai',                   'Emirate', true),
('AE','AE-FU','Fujairah',                'Emirate', true),
('AE','AE-RK','Ras al-Khaimah',          'Emirate', true),
('AE','AE-SH','Sharjah',                 'Emirate', true),
('AE','AE-UQ','Umm al-Quwain',           'Emirate', true),

-- ── United Kingdom ────────────────────────────────────────────────────
('GB','GB-ENG','England',                'Country',  true),
('GB','GB-NIR','Northern Ireland',       'Country',  true),
('GB','GB-SCT','Scotland',               'Country',  true),
('GB','GB-WLS','Wales',                  'Country',  true),

-- ── Germany — 16 Bundesländer ────────────────────────────────────────
('DE','DE-BB','Brandenburg',             'Bundesland', true),
('DE','DE-BE','Berlin',                  'Bundesland', true),
('DE','DE-BW','Baden-Württemberg',       'Bundesland', true),
('DE','DE-BY','Bavaria',                 'Bundesland', true),
('DE','DE-HB','Bremen',                  'Bundesland', true),
('DE','DE-HE','Hesse',                   'Bundesland', true),
('DE','DE-HH','Hamburg',                 'Bundesland', true),
('DE','DE-MV','Mecklenburg-Vorpommern',  'Bundesland', true),
('DE','DE-NI','Lower Saxony',            'Bundesland', true),
('DE','DE-NW','North Rhine-Westphalia',  'Bundesland', true),
('DE','DE-RP','Rhineland-Palatinate',    'Bundesland', true),
('DE','DE-SH','Schleswig-Holstein',      'Bundesland', true),
('DE','DE-SL','Saarland',                'Bundesland', true),
('DE','DE-SN','Saxony',                  'Bundesland', true),
('DE','DE-ST','Saxony-Anhalt',           'Bundesland', true),
('DE','DE-TH','Thuringia',               'Bundesland', true),

-- ── France — 13 Metropolitan Regions ─────────────────────────────────
('FR','FR-ARA','Auvergne-Rhône-Alpes',   'Region', true),
('FR','FR-BFC','Bourgogne-Franche-Comté','Region', true),
('FR','FR-BRE','Bretagne',               'Region', true),
('FR','FR-CVL','Centre-Val de Loire',    'Region', true),
('FR','FR-COR','Corse',                  'Region', true),
('FR','FR-GES','Grand Est',              'Region', true),
('FR','FR-HDF','Hauts-de-France',        'Region', true),
('FR','FR-IDF','Île-de-France',          'Region', true),
('FR','FR-NOR','Normandie',              'Region', true),
('FR','FR-NAQ','Nouvelle-Aquitaine',     'Region', true),
('FR','FR-OCC','Occitanie',              'Region', true),
('FR','FR-PDL','Pays de la Loire',       'Region', true),
('FR','FR-PAC','Provence-Alpes-Côte d''Azur','Region', true),

-- ── Australia — 6 States + 2 Territories ─────────────────────────────
('AU','AU-ACT','Australian Capital Territory','Territory', true),
('AU','AU-NSW','New South Wales',            'State',      true),
('AU','AU-NT', 'Northern Territory',         'Territory',  true),
('AU','AU-QLD','Queensland',                 'State',      true),
('AU','AU-SA', 'South Australia',            'State',      true),
('AU','AU-TAS','Tasmania',                   'State',      true),
('AU','AU-VIC','Victoria',                   'State',      true),
('AU','AU-WA', 'Western Australia',          'State',      true)

ON CONFLICT DO NOTHING;
