-- ============================================================
-- fn_seed_existing_company.sql
-- One-time seed for companies that existed before 007/008.
-- Inserts all currencies + countries as inactive, then
-- activates base_currency and local_currency from ric_companies.
--
-- USAGE (run in Supabase SQL Editor):
--   SELECT fn_seed_existing_company('your-company-uuid-here');
-- ============================================================

CREATE OR REPLACE FUNCTION fn_seed_existing_company(p_company_id uuid)
RETURNS text AS $$
DECLARE
    v_client_id  uuid;
    v_base       text;
    v_local      text;
    v_name       text;
BEGIN
    -- Look up the existing company
    SELECT client_id, base_currency, local_currency, company_name
    INTO   v_client_id, v_base, v_local, v_name
    FROM   ric_companies
    WHERE  id = p_company_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Company % not found in ric_companies', p_company_id;
    END IF;

    -- ── Seed currencies ───────────────────────────────────────────────────────

    INSERT INTO rim_currencies
        (client_id, company_id, currency_id, currency_name, currency_notation, currency_coin, country_code, is_active)
    VALUES
        (v_client_id, p_company_id, 'AED', 'UAE Dirham',                          'AED',  'Fils',           'AE', false),
        (v_client_id, p_company_id, 'AFN', 'Afghan Afghani',                      'Af',   'Pul',            'AF', false),
        (v_client_id, p_company_id, 'ALL', 'Albanian Lek',                        'L',    'Qindarkë',       'AL', false),
        (v_client_id, p_company_id, 'AMD', 'Armenian Dram',                       'AMD',  'Luma',           'AM', false),
        (v_client_id, p_company_id, 'ANG', 'Netherlands Antillean Guilder',       'ƒ',    'Cent',           'CW', false),
        (v_client_id, p_company_id, 'AOA', 'Angolan Kwanza',                      'Kz',   'Cêntimo',        'AO', false),
        (v_client_id, p_company_id, 'ARS', 'Argentine Peso',                      '$',    'Centavo',        'AR', false),
        (v_client_id, p_company_id, 'AUD', 'Australian Dollar',                   'A$',   'Cent',           'AU', false),
        (v_client_id, p_company_id, 'AWG', 'Aruban Florin',                       'ƒ',    'Cent',           'AW', false),
        (v_client_id, p_company_id, 'AZN', 'Azerbaijani Manat',                   '₼',    'Qəpik',          'AZ', false),
        (v_client_id, p_company_id, 'BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM',   'Fening',         'BA', false),
        (v_client_id, p_company_id, 'BBD', 'Barbadian Dollar',                    '$',    'Cent',           'BB', false),
        (v_client_id, p_company_id, 'BDT', 'Bangladeshi Taka',                    '৳',    'Paisa',          'BD', false),
        (v_client_id, p_company_id, 'BGN', 'Bulgarian Lev',                       'лв',   'Stotinka',       'BG', false),
        (v_client_id, p_company_id, 'BHD', 'Bahraini Dinar',                      'BD',   'Fils',           'BH', false),
        (v_client_id, p_company_id, 'BIF', 'Burundian Franc',                     'Fr',   NULL,             'BI', false),
        (v_client_id, p_company_id, 'BMD', 'Bermudian Dollar',                    '$',    'Cent',           'BM', false),
        (v_client_id, p_company_id, 'BND', 'Brunei Dollar',                       '$',    'Sen',            'BN', false),
        (v_client_id, p_company_id, 'BOB', 'Bolivian Boliviano',                  'Bs',   'Centavo',        'BO', false),
        (v_client_id, p_company_id, 'BRL', 'Brazilian Real',                      'R$',   'Centavo',        'BR', false),
        (v_client_id, p_company_id, 'BSD', 'Bahamian Dollar',                     '$',    'Cent',           'BS', false),
        (v_client_id, p_company_id, 'BTN', 'Bhutanese Ngultrum',                  'Nu',   'Chetrum',        'BT', false),
        (v_client_id, p_company_id, 'BWP', 'Botswana Pula',                       'P',    'Thebe',          'BW', false),
        (v_client_id, p_company_id, 'BYN', 'Belarusian Ruble',                    'Br',   'Kopek',          'BY', false),
        (v_client_id, p_company_id, 'BZD', 'Belize Dollar',                       '$',    'Cent',           'BZ', false),
        (v_client_id, p_company_id, 'CAD', 'Canadian Dollar',                     'CA$',  'Cent',           'CA', false),
        (v_client_id, p_company_id, 'CDF', 'Congolese Franc',                     'FC',   'Centime',        'CD', false),
        (v_client_id, p_company_id, 'CHF', 'Swiss Franc',                         'Fr',   'Rappen',         'CH', false),
        (v_client_id, p_company_id, 'CLP', 'Chilean Peso',                        '$',    'Centavo',        'CL', false),
        (v_client_id, p_company_id, 'CNY', 'Chinese Yuan',                        '¥',    'Fen',            'CN', false),
        (v_client_id, p_company_id, 'COP', 'Colombian Peso',                      '$',    'Centavo',        'CO', false),
        (v_client_id, p_company_id, 'CRC', 'Costa Rican Colón',                   '₡',    'Céntimo',        'CR', false),
        (v_client_id, p_company_id, 'CUP', 'Cuban Peso',                          '$',    'Centavo',        'CU', false),
        (v_client_id, p_company_id, 'CVE', 'Cape Verdean Escudo',                 'Esc',  'Centavo',        'CV', false),
        (v_client_id, p_company_id, 'CZK', 'Czech Koruna',                        'Kč',   'Haléř',          'CZ', false),
        (v_client_id, p_company_id, 'DJF', 'Djiboutian Franc',                    'Fr',   NULL,             'DJ', false),
        (v_client_id, p_company_id, 'DKK', 'Danish Krone',                        'kr',   'Øre',            'DK', false),
        (v_client_id, p_company_id, 'DOP', 'Dominican Peso',                      '$',    'Centavo',        'DO', false),
        (v_client_id, p_company_id, 'DZD', 'Algerian Dinar',                      'DA',   'Centime',        'DZ', false),
        (v_client_id, p_company_id, 'EGP', 'Egyptian Pound',                      '£',    'Piastre',        'EG', false),
        (v_client_id, p_company_id, 'ERN', 'Eritrean Nakfa',                      'Nfk',  'Cent',           'ER', false),
        (v_client_id, p_company_id, 'ETB', 'Ethiopian Birr',                      'Br',   'Santim',         'ET', false),
        (v_client_id, p_company_id, 'EUR', 'Euro',                                '€',    'Cent',           'EU', false),
        (v_client_id, p_company_id, 'FJD', 'Fijian Dollar',                       'FJ$',  'Cent',           'FJ', false),
        (v_client_id, p_company_id, 'FKP', 'Falkland Islands Pound',              '£',    'Penny',          'FK', false),
        (v_client_id, p_company_id, 'GBP', 'British Pound Sterling',              '£',    'Penny',          'GB', false),
        (v_client_id, p_company_id, 'GEL', 'Georgian Lari',                       '₾',    'Tetri',          'GE', false),
        (v_client_id, p_company_id, 'GHS', 'Ghanaian Cedi',                       '₵',    'Pesewa',         'GH', false),
        (v_client_id, p_company_id, 'GIP', 'Gibraltar Pound',                     '£',    'Penny',          'GI', false),
        (v_client_id, p_company_id, 'GMD', 'Gambian Dalasi',                      'D',    'Butut',          'GM', false),
        (v_client_id, p_company_id, 'GNF', 'Guinean Franc',                       'Fr',   NULL,             'GN', false),
        (v_client_id, p_company_id, 'GTQ', 'Guatemalan Quetzal',                  'Q',    'Centavo',        'GT', false),
        (v_client_id, p_company_id, 'GYD', 'Guyanese Dollar',                     '$',    'Cent',           'GY', false),
        (v_client_id, p_company_id, 'HKD', 'Hong Kong Dollar',                    'HK$',  'Cent',           'HK', false),
        (v_client_id, p_company_id, 'HNL', 'Honduran Lempira',                    'L',    'Centavo',        'HN', false),
        (v_client_id, p_company_id, 'HTG', 'Haitian Gourde',                      'G',    'Centime',        'HT', false),
        (v_client_id, p_company_id, 'HUF', 'Hungarian Forint',                    'Ft',   'Fillér',         'HU', false),
        (v_client_id, p_company_id, 'IDR', 'Indonesian Rupiah',                   'Rp',   'Sen',            'ID', false),
        (v_client_id, p_company_id, 'ILS', 'Israeli New Shekel',                  '₪',    'Agora',          'IL', false),
        (v_client_id, p_company_id, 'INR', 'Indian Rupee',                        '₹',    'Paisa',          'IN', false),
        (v_client_id, p_company_id, 'IQD', 'Iraqi Dinar',                         'IQD',  'Fils',           'IQ', false),
        (v_client_id, p_company_id, 'IRR', 'Iranian Rial',                        'Rls',  'Dinar',          'IR', false),
        (v_client_id, p_company_id, 'ISK', 'Icelandic Króna',                     'kr',   'Eyrir',          'IS', false),
        (v_client_id, p_company_id, 'JMD', 'Jamaican Dollar',                     '$',    'Cent',           'JM', false),
        (v_client_id, p_company_id, 'JOD', 'Jordanian Dinar',                     'JD',   'Fils',           'JO', false),
        (v_client_id, p_company_id, 'JPY', 'Japanese Yen',                        '¥',    NULL,             'JP', false),
        (v_client_id, p_company_id, 'KES', 'Kenyan Shilling',                     'KSh',  'Cent',           'KE', false),
        (v_client_id, p_company_id, 'KGS', 'Kyrgyzstani Som',                     'с',    'Tyiyn',          'KG', false),
        (v_client_id, p_company_id, 'KHR', 'Cambodian Riel',                      '៛',    'Sen',            'KH', false),
        (v_client_id, p_company_id, 'KMF', 'Comorian Franc',                      'Fr',   NULL,             'KM', false),
        (v_client_id, p_company_id, 'KPW', 'North Korean Won',                    '₩',    'Chon',           'KP', false),
        (v_client_id, p_company_id, 'KRW', 'South Korean Won',                    '₩',    NULL,             'KR', false),
        (v_client_id, p_company_id, 'KWD', 'Kuwaiti Dinar',                       'KD',   'Fils',           'KW', false),
        (v_client_id, p_company_id, 'KYD', 'Cayman Islands Dollar',               '$',    'Cent',           'KY', false),
        (v_client_id, p_company_id, 'KZT', 'Kazakhstani Tenge',                   '₸',    'Tiyin',          'KZ', false),
        (v_client_id, p_company_id, 'LAK', 'Lao Kip',                             '₭',    'Att',            'LA', false),
        (v_client_id, p_company_id, 'LBP', 'Lebanese Pound',                      'LL',   'Piastre',        'LB', false),
        (v_client_id, p_company_id, 'LKR', 'Sri Lankan Rupee',                    'Rs',   'Cent',           'LK', false),
        (v_client_id, p_company_id, 'LRD', 'Liberian Dollar',                     '$',    'Cent',           'LR', false),
        (v_client_id, p_company_id, 'LSL', 'Lesotho Loti',                        'L',    'Sente',          'LS', false),
        (v_client_id, p_company_id, 'LYD', 'Libyan Dinar',                        'LD',   'Dirham',         'LY', false),
        (v_client_id, p_company_id, 'MAD', 'Moroccan Dirham',                     'MAD',  'Centime',        'MA', false),
        (v_client_id, p_company_id, 'MDL', 'Moldovan Leu',                        'L',    'Ban',            'MD', false),
        (v_client_id, p_company_id, 'MGA', 'Malagasy Ariary',                     'Ar',   NULL,             'MG', false),
        (v_client_id, p_company_id, 'MKD', 'Macedonian Denar',                    'ден',  'Deni',           'MK', false),
        (v_client_id, p_company_id, 'MMK', 'Myanmar Kyat',                        'K',    'Pya',            'MM', false),
        (v_client_id, p_company_id, 'MNT', 'Mongolian Tögrög',                    '₮',    'Möngö',          'MN', false),
        (v_client_id, p_company_id, 'MOP', 'Macanese Pataca',                     'P',    'Avo',            'MO', false),
        (v_client_id, p_company_id, 'MRU', 'Mauritanian Ouguiya',                 'UM',   'Khoum',          'MR', false),
        (v_client_id, p_company_id, 'MUR', 'Mauritian Rupee',                     'Rs',   'Cent',           'MU', false),
        (v_client_id, p_company_id, 'MVR', 'Maldivian Rufiyaa',                   'Rf',   'Laari',          'MV', false),
        (v_client_id, p_company_id, 'MWK', 'Malawian Kwacha',                     'MK',   'Tambala',        'MW', false),
        (v_client_id, p_company_id, 'MXN', 'Mexican Peso',                        '$',    'Centavo',        'MX', false),
        (v_client_id, p_company_id, 'MYR', 'Malaysian Ringgit',                   'RM',   'Sen',            'MY', false),
        (v_client_id, p_company_id, 'MZN', 'Mozambican Metical',                  'MT',   'Centavo',        'MZ', false),
        (v_client_id, p_company_id, 'NAD', 'Namibian Dollar',                     '$',    'Cent',           'NA', false),
        (v_client_id, p_company_id, 'NGN', 'Nigerian Naira',                      '₦',    'Kobo',           'NG', false),
        (v_client_id, p_company_id, 'NIO', 'Nicaraguan Córdoba',                  'C$',   'Centavo',        'NI', false),
        (v_client_id, p_company_id, 'NOK', 'Norwegian Krone',                     'kr',   'Øre',            'NO', false),
        (v_client_id, p_company_id, 'NPR', 'Nepalese Rupee',                      'Rs',   'Paisa',          'NP', false),
        (v_client_id, p_company_id, 'NZD', 'New Zealand Dollar',                  'NZ$',  'Cent',           'NZ', false),
        (v_client_id, p_company_id, 'OMR', 'Omani Rial',                          'OMR',  'Baisa',          'OM', false),
        (v_client_id, p_company_id, 'PAB', 'Panamanian Balboa',                   'B/.',  'Centésimo',      'PA', false),
        (v_client_id, p_company_id, 'PEN', 'Peruvian Sol',                        'S/',   'Céntimo',        'PE', false),
        (v_client_id, p_company_id, 'PGK', 'Papua New Guinean Kina',              'K',    'Toea',           'PG', false),
        (v_client_id, p_company_id, 'PHP', 'Philippine Peso',                     '₱',    'Centavo',        'PH', false),
        (v_client_id, p_company_id, 'PKR', 'Pakistani Rupee',                     'Rs',   'Paisa',          'PK', false),
        (v_client_id, p_company_id, 'PLN', 'Polish Zloty',                        'zł',   'Grosz',          'PL', false),
        (v_client_id, p_company_id, 'PYG', 'Paraguayan Guaraní',                  '₲',    NULL,             'PY', false),
        (v_client_id, p_company_id, 'QAR', 'Qatari Riyal',                        'QR',   'Dirham',         'QA', false),
        (v_client_id, p_company_id, 'RON', 'Romanian Leu',                        'lei',  'Ban',            'RO', false),
        (v_client_id, p_company_id, 'RSD', 'Serbian Dinar',                       'din',  'Para',           'RS', false),
        (v_client_id, p_company_id, 'RUB', 'Russian Ruble',                       '₽',    'Kopek',          'RU', false),
        (v_client_id, p_company_id, 'RWF', 'Rwandan Franc',                       'Fr',   NULL,             'RW', false),
        (v_client_id, p_company_id, 'SAR', 'Saudi Riyal',                         'SR',   'Hallallah',      'SA', false),
        (v_client_id, p_company_id, 'SBD', 'Solomon Islands Dollar',              'SI$',  'Cent',           'SB', false),
        (v_client_id, p_company_id, 'SCR', 'Seychellois Rupee',                   'Rs',   'Cent',           'SC', false),
        (v_client_id, p_company_id, 'SDG', 'Sudanese Pound',                      '£',    'Piastre',        'SD', false),
        (v_client_id, p_company_id, 'SEK', 'Swedish Krona',                       'kr',   'Öre',            'SE', false),
        (v_client_id, p_company_id, 'SGD', 'Singapore Dollar',                    'S$',   'Cent',           'SG', false),
        (v_client_id, p_company_id, 'SHP', 'Saint Helena Pound',                  '£',    'Penny',          'SH', false),
        (v_client_id, p_company_id, 'SLE', 'Sierra Leonean Leone',                'Le',   'Cent',           'SL', false),
        (v_client_id, p_company_id, 'SOS', 'Somali Shilling',                     'Sh',   'Cent',           'SO', false),
        (v_client_id, p_company_id, 'SRD', 'Surinamese Dollar',                   '$',    'Cent',           'SR', false),
        (v_client_id, p_company_id, 'SSP', 'South Sudanese Pound',                '£',    'Piastre',        'SS', false),
        (v_client_id, p_company_id, 'STN', 'Sao Tome and Principe Dobra',         'Db',   'Centimo',        'ST', false),
        (v_client_id, p_company_id, 'SVC', 'Salvadoran Colon',                    '₡',    'Centavo',        'SV', false),
        (v_client_id, p_company_id, 'SYP', 'Syrian Pound',                        '£',    'Piastre',        'SY', false),
        (v_client_id, p_company_id, 'SZL', 'Swazi Lilangeni',                     'L',    'Cent',           'SZ', false),
        (v_client_id, p_company_id, 'THB', 'Thai Baht',                           '฿',    'Satang',         'TH', false),
        (v_client_id, p_company_id, 'TJS', 'Tajikistani Somoni',                  'SM',   'Diram',          'TJ', false),
        (v_client_id, p_company_id, 'TMT', 'Turkmenistani Manat',                 'T',    'Tennesi',        'TM', false),
        (v_client_id, p_company_id, 'TND', 'Tunisian Dinar',                      'DT',   'Millime',        'TN', false),
        (v_client_id, p_company_id, 'TOP', 'Tongan Paanga',                       'T$',   'Seniti',         'TO', false),
        (v_client_id, p_company_id, 'TRY', 'Turkish Lira',                        '₺',    'Kuruş',          'TR', false),
        (v_client_id, p_company_id, 'TTD', 'Trinidad and Tobago Dollar',          'TT$',  'Cent',           'TT', false),
        (v_client_id, p_company_id, 'TWD', 'New Taiwan Dollar',                   'NT$',  'Cent',           'TW', false),
        (v_client_id, p_company_id, 'TZS', 'Tanzanian Shilling',                  'Sh',   'Cent',           'TZ', false),
        (v_client_id, p_company_id, 'UAH', 'Ukrainian Hryvnia',                   '₴',    'Kopiyka',        'UA', false),
        (v_client_id, p_company_id, 'UGX', 'Ugandan Shilling',                    'Sh',   NULL,             'UG', false),
        (v_client_id, p_company_id, 'USD', 'US Dollar',                           '$',    'Cent',           'US', false),
        (v_client_id, p_company_id, 'UYU', 'Uruguayan Peso',                      '$',    'Centésimo',      'UY', false),
        (v_client_id, p_company_id, 'UZS', 'Uzbekistani Som',                     'UZS',  'Tiyin',          'UZ', false),
        (v_client_id, p_company_id, 'VES', 'Venezuelan Bolivar Soberano',         'Bs.S', 'Centimo',        'VE', false),
        (v_client_id, p_company_id, 'VND', 'Vietnamese Dong',                     '₫',    NULL,             'VN', false),
        (v_client_id, p_company_id, 'VUV', 'Vanuatu Vatu',                        'Vt',   NULL,             'VU', false),
        (v_client_id, p_company_id, 'WST', 'Samoan Tala',                         'T',    'Sene',           'WS', false),
        (v_client_id, p_company_id, 'XAF', 'Central African CFA Franc',           'Fr',   'Centime',        'CM', false),
        (v_client_id, p_company_id, 'XCD', 'East Caribbean Dollar',               '$',    'Cent',           'AG', false),
        (v_client_id, p_company_id, 'XOF', 'West African CFA Franc',              'Fr',   'Centime',        'SN', false),
        (v_client_id, p_company_id, 'XPF', 'CFP Franc',                           'Fr',   'Centime',        'PF', false),
        (v_client_id, p_company_id, 'YER', 'Yemeni Rial',                         'YR',   'Fils',           'YE', false),
        (v_client_id, p_company_id, 'ZAR', 'South African Rand',                  'R',    'Cent',           'ZA', false),
        (v_client_id, p_company_id, 'ZMW', 'Zambian Kwacha',                      'K',    'Ngwee',          'ZM', false),
        (v_client_id, p_company_id, 'ZWG', 'Zimbabwe Gold',                       'ZiG',  'Cent',           'ZW', false)
    ON CONFLICT (client_id, company_id, currency_id) DO NOTHING;

    -- Activate base and local currencies
    IF v_base IS NOT NULL THEN
        UPDATE rim_currencies SET is_active = true
        WHERE client_id = v_client_id AND company_id = p_company_id AND currency_id = v_base;
    END IF;
    IF v_local IS NOT NULL AND v_local <> COALESCE(v_base, '') THEN
        UPDATE rim_currencies SET is_active = true
        WHERE client_id = v_client_id AND company_id = p_company_id AND currency_id = v_local;
    END IF;

    -- ── Seed countries ────────────────────────────────────────────────────────

    INSERT INTO rim_countries
        (client_id, company_id, country_code, country_code_3, country_name, dial_code, region, default_currency_id, is_active)
    VALUES
        -- Africa
        (v_client_id, p_company_id, 'DZ', 'DZA', 'Algeria',                          '+213',  'Africa',   'DZD', false),
        (v_client_id, p_company_id, 'AO', 'AGO', 'Angola',                           '+244',  'Africa',   'AOA', false),
        (v_client_id, p_company_id, 'BJ', 'BEN', 'Benin',                            '+229',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'BW', 'BWA', 'Botswana',                         '+267',  'Africa',   'BWP', false),
        (v_client_id, p_company_id, 'BF', 'BFA', 'Burkina Faso',                     '+226',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'BI', 'BDI', 'Burundi',                          '+257',  'Africa',   'BIF', false),
        (v_client_id, p_company_id, 'CV', 'CPV', 'Cape Verde',                       '+238',  'Africa',   'CVE', false),
        (v_client_id, p_company_id, 'CM', 'CMR', 'Cameroon',                         '+237',  'Africa',   'XAF', false),
        (v_client_id, p_company_id, 'CF', 'CAF', 'Central African Republic',         '+236',  'Africa',   'XAF', false),
        (v_client_id, p_company_id, 'TD', 'TCD', 'Chad',                             '+235',  'Africa',   'XAF', false),
        (v_client_id, p_company_id, 'KM', 'COM', 'Comoros',                          '+269',  'Africa',   'KMF', false),
        (v_client_id, p_company_id, 'CD', 'COD', 'Democratic Republic of Congo',     '+243',  'Africa',   'CDF', false),
        (v_client_id, p_company_id, 'CG', 'COG', 'Republic of Congo',                '+242',  'Africa',   'XAF', false),
        (v_client_id, p_company_id, 'CI', 'CIV', 'Ivory Coast',                      '+225',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'DJ', 'DJI', 'Djibouti',                         '+253',  'Africa',   'DJF', false),
        (v_client_id, p_company_id, 'EG', 'EGY', 'Egypt',                            '+20',   'Africa',   'EGP', false),
        (v_client_id, p_company_id, 'GQ', 'GNQ', 'Equatorial Guinea',                '+240',  'Africa',   'XAF', false),
        (v_client_id, p_company_id, 'ER', 'ERI', 'Eritrea',                          '+291',  'Africa',   'ERN', false),
        (v_client_id, p_company_id, 'SZ', 'SWZ', 'Eswatini',                         '+268',  'Africa',   'SZL', false),
        (v_client_id, p_company_id, 'ET', 'ETH', 'Ethiopia',                         '+251',  'Africa',   'ETB', false),
        (v_client_id, p_company_id, 'GA', 'GAB', 'Gabon',                            '+241',  'Africa',   'XAF', false),
        (v_client_id, p_company_id, 'GM', 'GMB', 'Gambia',                           '+220',  'Africa',   'GMD', false),
        (v_client_id, p_company_id, 'GH', 'GHA', 'Ghana',                            '+233',  'Africa',   'GHS', false),
        (v_client_id, p_company_id, 'GN', 'GIN', 'Guinea',                           '+224',  'Africa',   'GNF', false),
        (v_client_id, p_company_id, 'GW', 'GNB', 'Guinea-Bissau',                    '+245',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'KE', 'KEN', 'Kenya',                            '+254',  'Africa',   'KES', false),
        (v_client_id, p_company_id, 'LS', 'LSO', 'Lesotho',                          '+266',  'Africa',   'LSL', false),
        (v_client_id, p_company_id, 'LR', 'LBR', 'Liberia',                          '+231',  'Africa',   'LRD', false),
        (v_client_id, p_company_id, 'LY', 'LBY', 'Libya',                            '+218',  'Africa',   'LYD', false),
        (v_client_id, p_company_id, 'MG', 'MDG', 'Madagascar',                       '+261',  'Africa',   'MGA', false),
        (v_client_id, p_company_id, 'MW', 'MWI', 'Malawi',                           '+265',  'Africa',   'MWK', false),
        (v_client_id, p_company_id, 'ML', 'MLI', 'Mali',                             '+223',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'MR', 'MRT', 'Mauritania',                       '+222',  'Africa',   'MRU', false),
        (v_client_id, p_company_id, 'MU', 'MUS', 'Mauritius',                        '+230',  'Africa',   'MUR', false),
        (v_client_id, p_company_id, 'MA', 'MAR', 'Morocco',                          '+212',  'Africa',   'MAD', false),
        (v_client_id, p_company_id, 'MZ', 'MOZ', 'Mozambique',                       '+258',  'Africa',   'MZN', false),
        (v_client_id, p_company_id, 'NA', 'NAM', 'Namibia',                          '+264',  'Africa',   'NAD', false),
        (v_client_id, p_company_id, 'NE', 'NER', 'Niger',                            '+227',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'NG', 'NGA', 'Nigeria',                          '+234',  'Africa',   'NGN', false),
        (v_client_id, p_company_id, 'RW', 'RWA', 'Rwanda',                           '+250',  'Africa',   'RWF', false),
        (v_client_id, p_company_id, 'ST', 'STP', 'Sao Tome and Principe',            '+239',  'Africa',   'STN', false),
        (v_client_id, p_company_id, 'SN', 'SEN', 'Senegal',                          '+221',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'SC', 'SYC', 'Seychelles',                       '+248',  'Africa',   'SCR', false),
        (v_client_id, p_company_id, 'SL', 'SLE', 'Sierra Leone',                     '+232',  'Africa',   'SLE', false),
        (v_client_id, p_company_id, 'SO', 'SOM', 'Somalia',                          '+252',  'Africa',   'SOS', false),
        (v_client_id, p_company_id, 'ZA', 'ZAF', 'South Africa',                     '+27',   'Africa',   'ZAR', false),
        (v_client_id, p_company_id, 'SS', 'SSD', 'South Sudan',                      '+211',  'Africa',   'SSP', false),
        (v_client_id, p_company_id, 'SD', 'SDN', 'Sudan',                            '+249',  'Africa',   'SDG', false),
        (v_client_id, p_company_id, 'TZ', 'TZA', 'Tanzania',                         '+255',  'Africa',   'TZS', false),
        (v_client_id, p_company_id, 'TG', 'TGO', 'Togo',                             '+228',  'Africa',   'XOF', false),
        (v_client_id, p_company_id, 'TN', 'TUN', 'Tunisia',                          '+216',  'Africa',   'TND', false),
        (v_client_id, p_company_id, 'UG', 'UGA', 'Uganda',                           '+256',  'Africa',   'UGX', false),
        (v_client_id, p_company_id, 'ZM', 'ZMB', 'Zambia',                           '+260',  'Africa',   'ZMW', false),
        (v_client_id, p_company_id, 'ZW', 'ZWE', 'Zimbabwe',                         '+263',  'Africa',   'ZWG', false),
        -- Americas
        (v_client_id, p_company_id, 'AG', 'ATG', 'Antigua and Barbuda',              '+1268', 'Americas', 'XCD', false),
        (v_client_id, p_company_id, 'AR', 'ARG', 'Argentina',                        '+54',   'Americas', 'ARS', false),
        (v_client_id, p_company_id, 'AW', 'ABW', 'Aruba',                            '+297',  'Americas', 'AWG', false),
        (v_client_id, p_company_id, 'BS', 'BHS', 'Bahamas',                          '+1242', 'Americas', 'BSD', false),
        (v_client_id, p_company_id, 'BB', 'BRB', 'Barbados',                         '+1246', 'Americas', 'BBD', false),
        (v_client_id, p_company_id, 'BZ', 'BLZ', 'Belize',                           '+501',  'Americas', 'BZD', false),
        (v_client_id, p_company_id, 'BM', 'BMU', 'Bermuda',                          '+1441', 'Americas', 'BMD', false),
        (v_client_id, p_company_id, 'BO', 'BOL', 'Bolivia',                          '+591',  'Americas', 'BOB', false),
        (v_client_id, p_company_id, 'BR', 'BRA', 'Brazil',                           '+55',   'Americas', 'BRL', false),
        (v_client_id, p_company_id, 'CA', 'CAN', 'Canada',                           '+1',    'Americas', 'CAD', false),
        (v_client_id, p_company_id, 'KY', 'CYM', 'Cayman Islands',                   '+1345', 'Americas', 'KYD', false),
        (v_client_id, p_company_id, 'CL', 'CHL', 'Chile',                            '+56',   'Americas', 'CLP', false),
        (v_client_id, p_company_id, 'CO', 'COL', 'Colombia',                         '+57',   'Americas', 'COP', false),
        (v_client_id, p_company_id, 'CR', 'CRI', 'Costa Rica',                       '+506',  'Americas', 'CRC', false),
        (v_client_id, p_company_id, 'CU', 'CUB', 'Cuba',                             '+53',   'Americas', 'CUP', false),
        (v_client_id, p_company_id, 'CW', 'CUW', 'Curacao',                          '+599',  'Americas', 'ANG', false),
        (v_client_id, p_company_id, 'DM', 'DMA', 'Dominica',                         '+1767', 'Americas', 'XCD', false),
        (v_client_id, p_company_id, 'DO', 'DOM', 'Dominican Republic',               '+1809', 'Americas', 'DOP', false),
        (v_client_id, p_company_id, 'EC', 'ECU', 'Ecuador',                          '+593',  'Americas', 'USD', false),
        (v_client_id, p_company_id, 'SV', 'SLV', 'El Salvador',                      '+503',  'Americas', 'USD', false),
        (v_client_id, p_company_id, 'FK', 'FLK', 'Falkland Islands',                 '+500',  'Americas', 'FKP', false),
        (v_client_id, p_company_id, 'GD', 'GRD', 'Grenada',                          '+1473', 'Americas', 'XCD', false),
        (v_client_id, p_company_id, 'GT', 'GTM', 'Guatemala',                        '+502',  'Americas', 'GTQ', false),
        (v_client_id, p_company_id, 'GY', 'GUY', 'Guyana',                           '+592',  'Americas', 'GYD', false),
        (v_client_id, p_company_id, 'HT', 'HTI', 'Haiti',                            '+509',  'Americas', 'HTG', false),
        (v_client_id, p_company_id, 'HN', 'HND', 'Honduras',                         '+504',  'Americas', 'HNL', false),
        (v_client_id, p_company_id, 'JM', 'JAM', 'Jamaica',                          '+1876', 'Americas', 'JMD', false),
        (v_client_id, p_company_id, 'MX', 'MEX', 'Mexico',                           '+52',   'Americas', 'MXN', false),
        (v_client_id, p_company_id, 'NI', 'NIC', 'Nicaragua',                        '+505',  'Americas', 'NIO', false),
        (v_client_id, p_company_id, 'PA', 'PAN', 'Panama',                           '+507',  'Americas', 'PAB', false),
        (v_client_id, p_company_id, 'PY', 'PRY', 'Paraguay',                         '+595',  'Americas', 'PYG', false),
        (v_client_id, p_company_id, 'PE', 'PER', 'Peru',                             '+51',   'Americas', 'PEN', false),
        (v_client_id, p_company_id, 'KN', 'KNA', 'Saint Kitts and Nevis',            '+1869', 'Americas', 'XCD', false),
        (v_client_id, p_company_id, 'LC', 'LCA', 'Saint Lucia',                      '+1758', 'Americas', 'XCD', false),
        (v_client_id, p_company_id, 'VC', 'VCT', 'Saint Vincent and the Grenadines', '+1784', 'Americas', 'XCD', false),
        (v_client_id, p_company_id, 'SR', 'SUR', 'Suriname',                         '+597',  'Americas', 'SRD', false),
        (v_client_id, p_company_id, 'TT', 'TTO', 'Trinidad and Tobago',              '+1868', 'Americas', 'TTD', false),
        (v_client_id, p_company_id, 'US', 'USA', 'United States',                    '+1',    'Americas', 'USD', false),
        (v_client_id, p_company_id, 'UY', 'URY', 'Uruguay',                          '+598',  'Americas', 'UYU', false),
        (v_client_id, p_company_id, 'VE', 'VEN', 'Venezuela',                        '+58',   'Americas', 'VES', false),
        -- Asia
        (v_client_id, p_company_id, 'AF', 'AFG', 'Afghanistan',                      '+93',   'Asia',     'AFN', false),
        (v_client_id, p_company_id, 'AM', 'ARM', 'Armenia',                          '+374',  'Asia',     'AMD', false),
        (v_client_id, p_company_id, 'AZ', 'AZE', 'Azerbaijan',                       '+994',  'Asia',     'AZN', false),
        (v_client_id, p_company_id, 'BH', 'BHR', 'Bahrain',                          '+973',  'Asia',     'BHD', false),
        (v_client_id, p_company_id, 'BD', 'BGD', 'Bangladesh',                       '+880',  'Asia',     'BDT', false),
        (v_client_id, p_company_id, 'BT', 'BTN', 'Bhutan',                           '+975',  'Asia',     'BTN', false),
        (v_client_id, p_company_id, 'BN', 'BRN', 'Brunei',                           '+673',  'Asia',     'BND', false),
        (v_client_id, p_company_id, 'KH', 'KHM', 'Cambodia',                         '+855',  'Asia',     'KHR', false),
        (v_client_id, p_company_id, 'CN', 'CHN', 'China',                            '+86',   'Asia',     'CNY', false),
        (v_client_id, p_company_id, 'GE', 'GEO', 'Georgia',                          '+995',  'Asia',     'GEL', false),
        (v_client_id, p_company_id, 'HK', 'HKG', 'Hong Kong',                        '+852',  'Asia',     'HKD', false),
        (v_client_id, p_company_id, 'IN', 'IND', 'India',                            '+91',   'Asia',     'INR', false),
        (v_client_id, p_company_id, 'ID', 'IDN', 'Indonesia',                        '+62',   'Asia',     'IDR', false),
        (v_client_id, p_company_id, 'IR', 'IRN', 'Iran',                             '+98',   'Asia',     'IRR', false),
        (v_client_id, p_company_id, 'IQ', 'IRQ', 'Iraq',                             '+964',  'Asia',     'IQD', false),
        (v_client_id, p_company_id, 'IL', 'ISR', 'Israel',                           '+972',  'Asia',     'ILS', false),
        (v_client_id, p_company_id, 'JP', 'JPN', 'Japan',                            '+81',   'Asia',     'JPY', false),
        (v_client_id, p_company_id, 'JO', 'JOR', 'Jordan',                           '+962',  'Asia',     'JOD', false),
        (v_client_id, p_company_id, 'KZ', 'KAZ', 'Kazakhstan',                       '+7',    'Asia',     'KZT', false),
        (v_client_id, p_company_id, 'KW', 'KWT', 'Kuwait',                           '+965',  'Asia',     'KWD', false),
        (v_client_id, p_company_id, 'KG', 'KGZ', 'Kyrgyzstan',                       '+996',  'Asia',     'KGS', false),
        (v_client_id, p_company_id, 'LA', 'LAO', 'Laos',                             '+856',  'Asia',     'LAK', false),
        (v_client_id, p_company_id, 'LB', 'LBN', 'Lebanon',                          '+961',  'Asia',     'LBP', false),
        (v_client_id, p_company_id, 'MO', 'MAC', 'Macau',                            '+853',  'Asia',     'MOP', false),
        (v_client_id, p_company_id, 'MY', 'MYS', 'Malaysia',                         '+60',   'Asia',     'MYR', false),
        (v_client_id, p_company_id, 'MV', 'MDV', 'Maldives',                         '+960',  'Asia',     'MVR', false),
        (v_client_id, p_company_id, 'MN', 'MNG', 'Mongolia',                         '+976',  'Asia',     'MNT', false),
        (v_client_id, p_company_id, 'MM', 'MMR', 'Myanmar',                          '+95',   'Asia',     'MMK', false),
        (v_client_id, p_company_id, 'NP', 'NPL', 'Nepal',                            '+977',  'Asia',     'NPR', false),
        (v_client_id, p_company_id, 'KP', 'PRK', 'North Korea',                      '+850',  'Asia',     'KPW', false),
        (v_client_id, p_company_id, 'OM', 'OMN', 'Oman',                             '+968',  'Asia',     'OMR', false),
        (v_client_id, p_company_id, 'PK', 'PAK', 'Pakistan',                         '+92',   'Asia',     'PKR', false),
        (v_client_id, p_company_id, 'PS', 'PSE', 'Palestine',                        '+970',  'Asia',     'ILS', false),
        (v_client_id, p_company_id, 'PH', 'PHL', 'Philippines',                      '+63',   'Asia',     'PHP', false),
        (v_client_id, p_company_id, 'QA', 'QAT', 'Qatar',                            '+974',  'Asia',     'QAR', false),
        (v_client_id, p_company_id, 'SA', 'SAU', 'Saudi Arabia',                     '+966',  'Asia',     'SAR', false),
        (v_client_id, p_company_id, 'SG', 'SGP', 'Singapore',                        '+65',   'Asia',     'SGD', false),
        (v_client_id, p_company_id, 'KR', 'KOR', 'South Korea',                      '+82',   'Asia',     'KRW', false),
        (v_client_id, p_company_id, 'LK', 'LKA', 'Sri Lanka',                        '+94',   'Asia',     'LKR', false),
        (v_client_id, p_company_id, 'SY', 'SYR', 'Syria',                            '+963',  'Asia',     'SYP', false),
        (v_client_id, p_company_id, 'TW', 'TWN', 'Taiwan',                           '+886',  'Asia',     'TWD', false),
        (v_client_id, p_company_id, 'TJ', 'TJK', 'Tajikistan',                       '+992',  'Asia',     'TJS', false),
        (v_client_id, p_company_id, 'TH', 'THA', 'Thailand',                         '+66',   'Asia',     'THB', false),
        (v_client_id, p_company_id, 'TL', 'TLS', 'Timor-Leste',                      '+670',  'Asia',     'USD', false),
        (v_client_id, p_company_id, 'TM', 'TKM', 'Turkmenistan',                     '+993',  'Asia',     'TMT', false),
        (v_client_id, p_company_id, 'TR', 'TUR', 'Turkey',                           '+90',   'Asia',     'TRY', false),
        (v_client_id, p_company_id, 'AE', 'ARE', 'United Arab Emirates',             '+971',  'Asia',     'AED', false),
        (v_client_id, p_company_id, 'UZ', 'UZB', 'Uzbekistan',                       '+998',  'Asia',     'UZS', false),
        (v_client_id, p_company_id, 'VN', 'VNM', 'Vietnam',                          '+84',   'Asia',     'VND', false),
        (v_client_id, p_company_id, 'YE', 'YEM', 'Yemen',                            '+967',  'Asia',     'YER', false),
        -- Europe
        (v_client_id, p_company_id, 'AL', 'ALB', 'Albania',                          '+355',  'Europe',   'ALL', false),
        (v_client_id, p_company_id, 'AD', 'AND', 'Andorra',                          '+376',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'AT', 'AUT', 'Austria',                          '+43',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'BY', 'BLR', 'Belarus',                          '+375',  'Europe',   'BYN', false),
        (v_client_id, p_company_id, 'BE', 'BEL', 'Belgium',                          '+32',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'BA', 'BIH', 'Bosnia and Herzegovina',           '+387',  'Europe',   'BAM', false),
        (v_client_id, p_company_id, 'BG', 'BGR', 'Bulgaria',                         '+359',  'Europe',   'BGN', false),
        (v_client_id, p_company_id, 'HR', 'HRV', 'Croatia',                          '+385',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'CY', 'CYP', 'Cyprus',                           '+357',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'CZ', 'CZE', 'Czech Republic',                   '+420',  'Europe',   'CZK', false),
        (v_client_id, p_company_id, 'DK', 'DNK', 'Denmark',                          '+45',   'Europe',   'DKK', false),
        (v_client_id, p_company_id, 'EE', 'EST', 'Estonia',                          '+372',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'FI', 'FIN', 'Finland',                          '+358',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'FR', 'FRA', 'France',                           '+33',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'DE', 'DEU', 'Germany',                          '+49',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'GI', 'GIB', 'Gibraltar',                        '+350',  'Europe',   'GIP', false),
        (v_client_id, p_company_id, 'GR', 'GRC', 'Greece',                           '+30',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'HU', 'HUN', 'Hungary',                          '+36',   'Europe',   'HUF', false),
        (v_client_id, p_company_id, 'IS', 'ISL', 'Iceland',                          '+354',  'Europe',   'ISK', false),
        (v_client_id, p_company_id, 'IE', 'IRL', 'Ireland',                          '+353',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'IT', 'ITA', 'Italy',                            '+39',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'XK', 'XKX', 'Kosovo',                           '+383',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'LV', 'LVA', 'Latvia',                           '+371',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'LI', 'LIE', 'Liechtenstein',                    '+423',  'Europe',   'CHF', false),
        (v_client_id, p_company_id, 'LT', 'LTU', 'Lithuania',                        '+370',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'LU', 'LUX', 'Luxembourg',                       '+352',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'MT', 'MLT', 'Malta',                            '+356',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'MD', 'MDA', 'Moldova',                          '+373',  'Europe',   'MDL', false),
        (v_client_id, p_company_id, 'MC', 'MCO', 'Monaco',                           '+377',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'ME', 'MNE', 'Montenegro',                       '+382',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'NL', 'NLD', 'Netherlands',                      '+31',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'MK', 'MKD', 'North Macedonia',                  '+389',  'Europe',   'MKD', false),
        (v_client_id, p_company_id, 'NO', 'NOR', 'Norway',                           '+47',   'Europe',   'NOK', false),
        (v_client_id, p_company_id, 'PL', 'POL', 'Poland',                           '+48',   'Europe',   'PLN', false),
        (v_client_id, p_company_id, 'PT', 'PRT', 'Portugal',                         '+351',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'RO', 'ROU', 'Romania',                          '+40',   'Europe',   'RON', false),
        (v_client_id, p_company_id, 'RU', 'RUS', 'Russia',                           '+7',    'Europe',   'RUB', false),
        (v_client_id, p_company_id, 'SM', 'SMR', 'San Marino',                       '+378',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'RS', 'SRB', 'Serbia',                           '+381',  'Europe',   'RSD', false),
        (v_client_id, p_company_id, 'SH', 'SHN', 'Saint Helena',                     '+290',  'Europe',   'SHP', false),
        (v_client_id, p_company_id, 'SK', 'SVK', 'Slovakia',                         '+421',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'SI', 'SVN', 'Slovenia',                         '+386',  'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'ES', 'ESP', 'Spain',                            '+34',   'Europe',   'EUR', false),
        (v_client_id, p_company_id, 'SE', 'SWE', 'Sweden',                           '+46',   'Europe',   'SEK', false),
        (v_client_id, p_company_id, 'CH', 'CHE', 'Switzerland',                      '+41',   'Europe',   'CHF', false),
        (v_client_id, p_company_id, 'UA', 'UKR', 'Ukraine',                          '+380',  'Europe',   'UAH', false),
        (v_client_id, p_company_id, 'GB', 'GBR', 'United Kingdom',                   '+44',   'Europe',   'GBP', false),
        (v_client_id, p_company_id, 'VA', 'VAT', 'Vatican City',                     '+39',   'Europe',   'EUR', false),
        -- Oceania
        (v_client_id, p_company_id, 'AU', 'AUS', 'Australia',                        '+61',   'Oceania',  'AUD', false),
        (v_client_id, p_company_id, 'FJ', 'FJI', 'Fiji',                             '+679',  'Oceania',  'FJD', false),
        (v_client_id, p_company_id, 'KI', 'KIR', 'Kiribati',                         '+686',  'Oceania',  'AUD', false),
        (v_client_id, p_company_id, 'MH', 'MHL', 'Marshall Islands',                 '+692',  'Oceania',  'USD', false),
        (v_client_id, p_company_id, 'FM', 'FSM', 'Micronesia',                       '+691',  'Oceania',  'USD', false),
        (v_client_id, p_company_id, 'NR', 'NRU', 'Nauru',                            '+674',  'Oceania',  'AUD', false),
        (v_client_id, p_company_id, 'NZ', 'NZL', 'New Zealand',                      '+64',   'Oceania',  'NZD', false),
        (v_client_id, p_company_id, 'PW', 'PLW', 'Palau',                            '+680',  'Oceania',  'USD', false),
        (v_client_id, p_company_id, 'PG', 'PNG', 'Papua New Guinea',                 '+675',  'Oceania',  'PGK', false),
        (v_client_id, p_company_id, 'WS', 'WSM', 'Samoa',                            '+685',  'Oceania',  'WST', false),
        (v_client_id, p_company_id, 'SB', 'SLB', 'Solomon Islands',                  '+677',  'Oceania',  'SBD', false),
        (v_client_id, p_company_id, 'TO', 'TON', 'Tonga',                            '+676',  'Oceania',  'TOP', false),
        (v_client_id, p_company_id, 'TV', 'TUV', 'Tuvalu',                           '+688',  'Oceania',  'AUD', false),
        (v_client_id, p_company_id, 'VU', 'VUT', 'Vanuatu',                          '+678',  'Oceania',  'VUV', false)
    ON CONFLICT (client_id, company_id, country_code) DO NOTHING;

    RETURN format('Seeded currencies and countries for company "%s" (%s). Base: %s | Local: %s',
                  v_name, p_company_id, COALESCE(v_base, 'not set'), COALESCE(v_local, 'not set'));
END;
$$ LANGUAGE plpgsql;
